"""new fields in user model

Revision ID: 265c2bf3cb1a
Revises: 4aefafed82c7
Create Date: 2018-12-30 15:02:52.718112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265c2bf3cb1a'
down_revision = '4aefafed82c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
