"""New tables added

Revision ID: a51714943b54
Revises: f0bc3c4be9eb
Create Date: 2019-01-10 18:37:41.704542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51714943b54'
down_revision = 'f0bc3c4be9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=9), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('match', sa.Column('last_update', sa.DateTime(), nullable=True))
    op.add_column('match', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'match', 'match_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'match', 'season', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'status_id')
    op.drop_column('match', 'season_id')
    op.drop_column('match', 'last_update')
    op.drop_table('result')
    op.drop_table('season')
    op.drop_table('match_status')
    op.drop_table('league')
    # ### end Alembic commands ###
